import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

/**
 * DEMO EXPERIENCE NOTE
 * --------------------
 * The "Instant Website Snapshot" is a front-end demo: the score and metrics are
 * simulated locally, while the insight lines below are genuinely generated by an
 * LLM from whatever the visitor typed. This is NOT a real crawl/audit of the site.
 * To make it real later, replace this handler with a call to a live audit API
 * (Lighthouse/PageSpeed, etc.) and feed those results into the same prompt.
 */

const InputSchema = z.object({
  target: z.string().trim().min(2).max(120),
});

const FALLBACK = [
  "Your homepage message doesn't state what you sell within the first screen.",
  "No clear call-to-action above the fold — visitors have nothing obvious to click.",
  "Mobile layout likely costs you conversions on the majority of your traffic.",
  "No visible lead capture, so interested visitors leave without a trace.",
];

export const generateInsights = createServerFn({ method: "POST" })
  .inputValidator((input: unknown) => InputSchema.parse(input))
  .handler(async ({ data }) => {
    const key = process.env["LOVABLE_API_KEY"];
    if (!key) return { insights: FALLBACK, simulated: true };

    try {
      const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${key}`,
        },
        body: JSON.stringify({
          model: "google/gemini-3.7-flash",
          messages: [
            {
              role: "system",
              content:
                "You are a blunt web-performance and conversion analyst for an agency called Shakik Industries. " +
                "Given a website URL or a business name/industry, produce exactly 4 short, specific, plausible " +
                "audit-style observations about their likely digital presence. Each line max 14 words, plain English, " +
                "no markdown, no numbering, one per line. Mix speed, messaging, mobile UX, SEO and lead capture.",
            },
            { role: "user", content: `Target: ${data.target}` },
          ],
        }),
      });

      if (!res.ok) {
        // 429/5xx are transient; anything else is terminal. Either way, degrade gracefully.
        console.error("AI gateway error", res.status, await res.text());
        return { insights: FALLBACK, simulated: true };
      }

      const json = (await res.json()) as {
        choices?: Array<{ message?: { content?: string } }>;
      };
      const text = json.choices?.[0]?.message?.content ?? "";
      const lines = text
        .split("\n")
        .map((l) => l.replace(/^[-*\d.\s]+/, "").trim())
        .filter(Boolean)
        .slice(0, 4);

      return { insights: lines.length >= 3 ? lines : FALLBACK, simulated: false };
    } catch (err) {
      console.error("insight generation failed", err);
      return { insights: FALLBACK, simulated: true };
    }
  });
