import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { ActivitySquare, Loader2, Radar } from "lucide-react";
import { generateInsights } from "@/lib/insights.functions";
import { Reveal } from "./Reveal";
import { SectionHeading } from "./SectionHeading";

/**
 * INSTANT WEBSITE SNAPSHOT — front-end demo experience.
 *
 * The score, the sub-metrics and the loading sequence are simulated in this component
 * (mock / randomised output). The 3–4 insight lines ARE generated by an LLM from the
 * URL or business name the visitor types, via the `generateInsights` server function.
 * This is NOT a real live audit — swap in a real audit API later and feed those numbers
 * into `score` / `metrics` below plus the server-side prompt.
 */

type Phase = "idle" | "scanning" | "done";

const STAGES = ["Resolving target", "Sampling page weight", "Modelling visitor flow", "Compiling report"];

export function AiSnapshot() {
  const analyze = useServerFn(generateInsights);
  const [target, setTarget] = useState("");
  const [phase, setPhase] = useState<Phase>("idle");
  const [progress, setProgress] = useState(0);
  const [stage, setStage] = useState(0);
  const [score, setScore] = useState(0);
  const [insights, setInsights] = useState<string[]>([]);
  const [metrics, setMetrics] = useState<{ k: string; v: string }[]>([]);

  const run = async (e: React.FormEvent) => {
    e.preventDefault();
    if (target.trim().length < 2 || phase === "scanning") return;

    setPhase("scanning");
    setProgress(0);
    setStage(0);
    setInsights([]);

    const timer = setInterval(() => {
      setProgress((p) => {
        const next = Math.min(p + 4 + Math.random() * 6, 96);
        setStage(Math.min(Math.floor(next / 25), STAGES.length - 1));
        return next;
      });
    }, 130);

    let lines: string[] = [];
    try {
      const res = await analyze({ data: { target: target.trim() } });
      lines = res.insights;
    } catch {
      lines = [
        "Homepage message isn't clear within the first screen.",
        "No obvious call-to-action above the fold.",
        "Mobile experience likely needs improvement.",
      ];
    }

    // simulated scoring — replace with real audit data when wiring a live API
    await new Promise((r) => setTimeout(r, 900));
    clearInterval(timer);
    setProgress(100);
    setScore(58 + Math.floor(Math.random() * 32));
    setMetrics([
      { k: "Load speed", v: `${(1.4 + Math.random() * 2.6).toFixed(1)}s` },
      { k: "Mobile score", v: `${52 + Math.floor(Math.random() * 40)}/100` },
      { k: "Conversion paths", v: `${1 + Math.floor(Math.random() * 3)}` },
    ]);
    setInsights(lines.slice(0, 4));
    setPhase("done");
  };

  return (
    <section
      id="insights"
      className="relative overflow-hidden border-y border-border bg-card/30 py-24 md:py-32"
    >
      <div className="blueprint-grid pointer-events-none absolute inset-0 opacity-50" />
      <div className="pointer-events-none absolute top-1/3 -right-40 h-[420px] w-[520px] rounded-full bg-signal/10 blur-[150px]" />

      <div className="relative mx-auto grid max-w-7xl gap-12 px-5 md:px-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-center">
        <Reveal>
          <SectionHeading
            index="03 / AI Insights"
            title="Your business, read by machine."
            subtitle="Every Shakik site is wired into an insight engine that watches traffic, visitors and conversion behaviour — then tells you what to do about it in plain English. Try a live snapshot."
          />
        </Reveal>

        <Reveal delay={120}>
          <div className="cut-corner border border-border bg-background/70 p-5 shadow-[var(--shadow-panel)] backdrop-blur sm:p-7">
            <div className="flex items-center justify-between border-b border-border pb-4">
              <span className="font-display flex items-center gap-2 text-[10px] tracking-[0.28em] text-muted-foreground">
                <Radar className="h-4 w-4 text-signal" strokeWidth={1.6} />
                Instant Website Snapshot
              </span>
              <span className="font-display text-[10px] tracking-[0.25em] text-signal">Demo</span>
            </div>

            <form onSubmit={run} className="mt-5 flex flex-col gap-3 sm:flex-row">
              <input
                value={target}
                onChange={(e) => setTarget(e.target.value)}
                placeholder="yourdomain.com — or your business & industry"
                maxLength={120}
                className="cut-corner-sm w-full border border-input bg-card px-4 py-3.5 text-sm text-foreground outline-none placeholder:text-muted-foreground/70 focus:border-signal"
              />
              <button
                type="submit"
                disabled={phase === "scanning"}
                className="cut-btn font-display flex items-center justify-center gap-2 bg-signal px-7 py-3.5 text-xs tracking-[0.22em] text-signal-foreground disabled:opacity-60"
              >
                {phase === "scanning" ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
                Analyze
              </button>
            </form>

            {phase === "scanning" && (
              <div className="mt-6">
                <div className="h-1 w-full bg-muted">
                  <div
                    className="h-1 bg-signal transition-all duration-150"
                    style={{ width: `${progress}%` }}
                  />
                </div>
                <div className="font-display mt-3 text-[10px] tracking-[0.25em] text-muted-foreground">
                  {STAGES[stage]}…
                </div>
                <div className="mt-5 space-y-3">
                  {[0, 1, 2, 3].map((i) => (
                    <div key={i} className="h-3.5 w-full animate-pulse bg-muted" />
                  ))}
                </div>
              </div>
            )}

            {phase === "done" && (
              <div className="mt-6">
                <div className="cut-corner-sm flex flex-wrap items-center justify-between gap-4 border border-border bg-card/70 p-4">
                  <div>
                    <div className="text-[10px] tracking-[0.24em] text-muted-foreground uppercase">
                      Digital Presence Score
                    </div>
                    <div className="font-display chrome-text mt-1 text-4xl">{score}/100</div>
                  </div>
                  <div className="flex gap-4">
                    {metrics.map((m) => (
                      <div key={m.k}>
                        <div className="text-[9px] tracking-[0.18em] text-muted-foreground uppercase">
                          {m.k}
                        </div>
                        <div className="font-display mt-1 text-sm text-signal">{m.v}</div>
                      </div>
                    ))}
                  </div>
                </div>

                <ul className="mt-5 space-y-3">
                  {insights.map((line, i) => (
                    <li key={i} className="flex gap-3 text-sm leading-relaxed text-foreground/85">
                      <ActivitySquare
                        className="mt-0.5 h-4 w-4 shrink-0 text-signal"
                        strokeWidth={1.6}
                      />
                      {line}
                    </li>
                  ))}
                </ul>

                <a
                  href="#contact"
                  className="cut-btn font-display mt-7 block border border-signal/60 px-6 py-4 text-center text-xs tracking-[0.2em] text-signal transition-colors hover:bg-signal hover:text-signal-foreground"
                >
                  Get the full report — talk to us
                </a>
                <p className="mt-3 text-[11px] text-muted-foreground">
                  Snapshot is an indicative demo. A full Shakik audit reviews live performance data.
                </p>
              </div>
            )}
          </div>
        </Reveal>
      </div>
    </section>
  );
}
